Implemented --cron option, but not working yet.
These changes cause errors using rustc 1.56.0 (09c42c458 2021-10-18):

   Compiling phoenix_cmc v0.1.0 (/home/deven/git/phoenix)
error[E0277]: `?` couldn't convert the error to `Box<std::io::Error>`
   --> src/main.rs:91:96
    |
91  |         .with_env_filter(EnvFilter::from_default_env().add_directive("phoenix_cmc=info".parse()?))
    |                                                                                                ^ the trait `From<ParseError>` is not implemented for `Box<std::io::Error>`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <Box<(dyn std::error::Error + 'a)> as From<E>>
              <Box<(dyn std::error::Error + 'static)> as From<&str>>
              <Box<(dyn std::error::Error + 'static)> as From<Cow<'a, str>>>
              <Box<(dyn std::error::Error + 'static)> as From<String>>
            and 22 others
    = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, ParseError>>` for `Result<(), Box<std::io::Error>>`
note: required by `from_residual`

error[E0308]: mismatched types
   --> src/main.rs:116:5
    |
88  |   async fn main() -> Result<(), Box<dyn Error>> {
    |                      -------------------------- expected `Result<(), Box<(dyn std::error::Error + 'static)>>` because of return type
...
116 | /     loop {
117 | |         match listener.accept().await {
118 | |             Ok((socket, addr)) => {
119 | |                 info!("Accepted TCP connection from {:?}", addr);
...   |
130 | |         }
131 | |     }
    | |_____^ expected trait object `dyn std::error::Error`, found struct `std::io::Error`
    |
    = note: expected enum `Result<_, Box<(dyn std::error::Error + 'static)>>`
               found enum `Result<_, Box<std::io::Error>>`

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `phoenix_cmc` due to 2 previous errors